// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly VITE_API_URL: string;
  readonly VITE_AUTH_API_URL: string;
  readonly VITE_API_USERNAME: string;
  readonly VITE_HOME_BASE_URL: string;
  readonly VITE_API_PASSWORD: string;
  readonly VITE_API_WS_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
